### ISSUE TITLE
LanguageClient Qode Assist: Error -32803: The server is currently in an unreachable state.

### ISSUE THREAD

**Issue by argi98** [Palm1r/QodeAssist#17]
Qt Creator 14.0.2
Based on Qt 6.7.3 (Clang 14.0 (Apple), arm64)
qt 5.12.2

![image](https://github.com/user-attachments/assets/a4c89199-225d-4746-8f4d-1efed7b03059)
![image](https://github.com/user-attachments/assets/af8ac2e6-2f6a-45a2-8898-c29fd1121e42)
![image](https://github.com/user-attachments/assets/3bb1e8f4-d865-4dd9-82da-27466ece88bc)

[QodeAssist-14.0.0-macOS-universal.7z](https://github.com/Palm1r/QodeAssist/releases/download/v0.2.2/QodeAssist-14.0.0-macOS-universal.7z)

Qt Creator hang on exit, when QodeAssist plugin is loaded.
Code assist and auto complete not working.

While writing code I don't see statements in Ollama logs, instead in General Messages it shows "LanguageClient Qode Assist: Error -32803: The server is currently in an unreachable state."

The Ollama server is working properly on http://localhost:11434/ and shows: "Ollama is running"

**Comment by Palm1r** [comment]
Thank you for issue, this problem related with QtCreator 14.0.2 update, I will fix it soon

**Comment by Palm1r** [comment]
@argi98 please check latest 0.2.3 version
