### ISSUE TITLE
Code formatting in the QodeAssist codebase

### ISSUE THREAD

**Issue by SidneyCogdill** [Palm1r/QodeAssist#31]
Qt Creator comes with multiple code formatting tool integrations bundled, including `clang-format` for C/C++, `qmlformat` for QML, `cmake-format` for CMake files.

If I leave the "auto formatting on save" options enabled while editing QodeAssist sources, then the formatting tools will kick in and re-edit the whole file, the diff on the submitted patches will be full of re-formatting noises instead of highlighting the relevant changes.

Therefore it would be helpful if the codebase decides to explicitly opt into code formatting tools and provide a customized `.qmlformat.ini` and `.clang-format` in the project directory, so that the automatic formatting tools can respect the project's code formatting style.

Note that for `cmake-format` it doesn't seem to have the concept of a project-scope configuration file and have to manually pass the config file path as the command line option.

**Comment by Palm1r** [comment]
Thank you for good idea,  I agree, will add soon

**Comment by Palm1r** [comment]
@SidneyCogdill I added .clang-format file for full formatting and .qmlformat.ini for only space formatting. I don't like how works normalize now and added link to qml code style  https://github.com/Furkanzmc/QML-Coding-Guide, I think it is best. What do you suggest for cmake-format? It is new for me
