### ISSUE TITLE
I got an error when installed

### ISSUE THREAD

**Issue by atakli** [Palm1r/QodeAssist#47]
![image](https://github.com/user-attachments/assets/4c3e0832-b58e-420b-bad9-fee7c3d12a88)

My Qt Creator version is 13.0.2

**Comment by Palm1r** [comment]
QodeAssist doesn't support QtCreator 13

**Comment by atakli** [comment]
thank you it was installed when I upgraded qt creator to version 15. chat is working but auto completion is not. what am i missing?

**Comment by Palm1r** [comment]
What model did you install? maybe call autocomplete by hotkey will help?

**Comment by atakli** [comment]
I installed llama3.2:latest. Hotkey also does not work. my configuration is this:

![image](https://github.com/user-attachments/assets/137c69d4-ff38-4a07-aae5-d354c377cca0)

**Comment by atakli** [comment]
I changed the template to StarCoder2 FIM and it worked. But it gives very wrong output

**Comment by Palm1r** [comment]
llama doesn't have code completion via FIM template. For now QodeAssist supports only models with FIM, like Codellama, Qwen, Starcoder2
