### ISSUE TITLE
From source under Linux not work: Did not find Qt Creator plugin.

### ISSUE THREAD

**Issue by alphaonex86** [Palm1r/QodeAssist#50]
**Describe the bug**
From source under Linux not work: Did not find Qt Creator plugin.
I need be compiled, clarify and provide command to compile under Linux

**Desktop (please complete the following information):**
 - OS: Linux Gentoo
 - Qt Creator: 14.0.2

**Comment by Palm1r** [comment]
Latest version support only QtCreator 15

**Comment by Palm1r** [comment]
yes, thank you, git cached wrong name. Sorry. Fix has been pushed

**Comment by alphaonex86** [comment]
ok, with 0.3 version, Test button not work, just do nothing, maybe lack of error message in case of problem. All my ollama installation is working.

**Comment by Palm1r** [comment]
yes, test button is for future cases. Please send setup of QodeAssist and enable log

**Comment by alphaonex86** [comment]
What do you need for **Please send setup**?
The logs: 10:34:02.659 default: content-type missing in HTTP POST, defaulting to application/x-www-form-urlencoded. Use QNetworkRequest::setHeader() to fix this problem.

**Comment by Palm1r** [comment]
I meant setup from settings of QodeAssist: 
provider
url
model
template

**Comment by alphaonex86** [comment]
Provider: Ollama
Url: http://localhost:11434
Model: qwen2.5-coder:32b
Ollama Auto FIM
Work perfectly with my other Qt software.

**Comment by Palm1r** [comment]
Did you check 0.3.10 version?

**Comment by Palm1r** [comment]
Please try branch [backport-to-qtc14](https://github.com/Palm1r/QodeAssist/tree/backport-to-qtc14)

**Comment by alphaonex86** [comment]
Now not have this warning but remain with work.
Hotkeys of readme not mention Linux.
Should be useful have the test button working for this case

**Comment by Palm1r** [comment]
There is a small button for call code completion in the right down corner of QtCreator, you can try
<img width="163" alt="Screenshot 2024-12-12 at 16 16 03" src="https://github.com/user-attachments/assets/ab5a2451-dd1d-4959-92ef-8adf960ccccb" />

Any logs in General messages? If log is enabled in settings, in general messages you can see messages to Ollama and answers

I see hot key in settings
<img width="738" alt="Screenshot 2024-12-12 at 16 18 53" src="https://github.com/user-attachments/assets/ace3c325-8e66-4759-bc84-d7056efbadf5" />

Yes, test button will be useful when will be released

**Comment by alphaonex86** [comment]
Ok, I have to click on the globe.
Automatic seam not work, then bug closed.
The point to improve:

- test button
- multiline
- automatic
